alias gd='git diff --ignore-submodules=dirty --color | sed "s/^\([^-+ ]*\)[-+ ]/\\1/" | less -r'
alias gst='git status -sb --ignore-submodules=dirty'
alias gp='git pull --rebase'
alias gb='git branch'
alias glog='git log --format="%Cgreen%h%Creset %C(cyan)%an%Creset - %s %Cgreen(%cr)%Creset" --graph --date=relative'
alias gco='git checkout'
alias gpurge='git branch | grep -v "master" | grep -v "main" | xargs git branch -D'
