alias server='simplehttpserver . & open http://localhost:8000 && fg'
alias speedtest='wget --report-speed=bits -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test10.zip'
alias reload='. ~/.zshrc'
alias weather='curl http://wttr.in/'
alias moon='curl http://us.wttr.in/moon'
alias flushdns='sudo killall -HUP mDNSResponder'
alias whodat='whois -h whois.arin.net'
alias deploy='npm run deploy'
alias deploy_env='npm run update-env; npm run deploy'
alias dstroy='find . -name ".DS_Store" -type f -delete'
